apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-exporter
  labels:
    snappyflow/compname: esstage
    snappyflow/appname: test-es-stage
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: {{ template "fullname" . }}
    role: exporter
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: {{ template "fullname" . }}
      role: exporter
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        snappyflow/compname: esstage
        snappyflow/appname: test-es-stage
        release: "{{ .Release.Name }}"
        component: {{ template "fullname" . }}
        role: exporter
    spec:
      restartPolicy: {{ .Values.exporter.restartPolicy }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: "{{ .Chart.Name }}-exporter"
          image: "{{ .Values.exporter.image.repository }}:{{ .Values.exporter.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["elasticsearch_exporter",
                    "-es.uri=http://{{ template "fullname" . }}:9200",
                    "-es.all={{ .Values.exporter.es.all }}",
                    "-es.indices={{ .Values.exporter.es.indices }}",
                    "-es.timeout={{ .Values.exporter.es.timeout }}",
                    "-web.listen-address=:{{ .Values.exporter.service.httpPort }}",
                    "-web.telemetry-path={{ .Values.exporter.web.path }}"]
          securityContext:
            capabilities:
              drop:
                - SETPCAP
                - MKNOD
                - AUDIT_WRITE
                - CHOWN
                - NET_RAW
                - DAC_OVERRIDE
                - FOWNER
                - FSETID
                - KILL
                - SETGID
                - SETUID
                - NET_BIND_SERVICE
                - SYS_CHROOT
                - SETFCAP
            readOnlyRootFilesystem: true
          resources:
{{ toYaml .Values.resources | indent 12 }}
          ports:
            - containerPort: {{ .Values.service.httpPort }}
              name: exporter
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 10
